spring:
  jpa:
    hibernate:
      ddl-auto: update
    # 개발시 SQL 로깅을 하여 어떤 값으로 어떤 SQL이 실행되는지 확인합니다.
    properties:
      hibernate:
        format_sql: true
    #Controller에서 엔티티 매니저를 사용한 Lazy로딩을 하지 못하도록 막
    open-in-view: false
  datasource:
    driver-class-name: org.postgresql.Driver
    username: lyl
    url: jdbc:postgresql://lyl-database.c6lllniau47k.ap-northeast-2.rds.amazonaws.com:5432/lyl
    password: lyldatabase

logging:
  level:
    org.hibernate:
      SQL: DEBUG
      type.descriptor.sql.BasicBinder: TRACE

server:
  port: 8089
  tomcat:
    max-http-form-post-size: 5MB
