spring:
  profiles.active: local

  # 개발할 때에만 create-drop 또는 update를 사용하고 운영 환경에서는 validate를 사용합니다.
  jpa:
    hibernate:
      ddl-auto: create-drop
    # 개발시 SQL 로깅을 하여 어떤 값으로 어떤 SQL이 실행되는지 확인합니다.
    properties:
      hibernate:
        format_sql: true
    #Controller에서 엔티티 매니저를 사용한 Lazy로딩을 하지 못하도록 막
    open-in-view: false
  # HTML <FORM>에서 th:method에서 PUT 또는 DELETE를 사용해서 보내는 _method를 사용해서  @PutMapping과 @DeleteMapping으로 요청을 맵핑.

logging:
  level:
    org.hibernate:
      SQL: DEBUG
      type.descriptor.sql.BasicBinder: TRACE

# 톰캣 기본 요청 사이즈는 2MB 입니다. 그것보다 큰 요청을 받고 싶은 경우에 이 값을 조정해야 합니다.
server:
  port: 8080
  tomcat:
    max-http-form-post-size: 5MB
